version: '3'

services:
  test-archlinux:
    image: archlinux:base-devel
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/archlinux.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-ubuntu-22.04:
    image: ubuntu:22.04
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/ubuntu-22.04.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-ubuntu-20.04:
    image: ubuntu:20.04
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/ubuntu-20.04.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-ubuntu-18.04:
    image: ubuntu:20.04
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/ubuntu-18.04.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-ubuntu-16.04:
    image: ubuntu:16.04
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/ubuntu-16.04.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-ubuntu-14.04:
    image: ubuntu:16.04
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/ubuntu-14.04.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-debian-11:
    image: debian:11
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/debian-11.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-debian-10:
    image: debian:10
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/debian-10.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-debian-9:
    image: debian:9
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/debian-9.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-openwrtorg:
    build:
      context: ./docker/openwrtorg
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/openwrtorg.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-fedora-37:
    build:
      context: ./docker/fedora/37
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/fedora-37.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-fedora-36:
    build:
      context: ./docker/fedora/36
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/fedora-36.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-fedora-35:
    build:
      context: ./docker/fedora/35
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/fedora-35.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-fedora-34:
    build:
      context: ./docker/fedora/34
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/fedora-34.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-centos-7:
    image: centos:7
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/centos-7.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-redhat-9:
    build:
      context: ./docker/redhat/9
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/redhat-9.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  test-redhat-8:
    build:
      context: ./docker/redhat/8
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/redhat-8.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data:ro
  opensuse-tumbleweed:
    build:
      context: ./docker/opensuse/tumbleweed
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/opensuse-tumbleweed.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data
  opensuse-leap-15:
    build:
      context: ./docker/opensuse/leap/15
    command: ["bash", "-c", "bash /tmp/dist/pkgtop.sh 25 80 -r | diff /tmp/data/opensuse-leap-15.txt -"]
    volumes:
      - ./dist:/tmp/dist:ro
      - ./data:/tmp/data
