version: '3'

services:
  archlinux:
    extends:
      file: docker-tests-base.yml
      service: run
    image: archlinux:base-devel
    volumes:
      - ./fixtures/archlinux:/fixtures:ro
  ubuntu-22.04:
    extends:
      file: docker-tests-base.yml
      service: run
    image: ubuntu:22.04
    volumes:
      - ./fixtures/ubuntu-22.04:/fixtures:ro
  ubuntu-20.04:
    extends:
      file: docker-tests-base.yml
      service: run
    image: ubuntu:20.04
    volumes:
      - ./fixtures/ubuntu-20.04:/fixtures:ro
  ubuntu-18.04:
    extends:
      file: docker-tests-base.yml
      service: run
    image: ubuntu:18.04
    volumes:
      - ./fixtures/ubuntu-18.04:/fixtures:ro
  ubuntu-16.04:
    extends:
      file: docker-tests-base.yml
      service: run
    image: ubuntu:16.04
    volumes:
      - ./fixtures/ubuntu-16.04:/fixtures:ro
  ubuntu-14.04:
    extends:
      file: docker-tests-base.yml
      service: run
    image: ubuntu:14.04
    volumes:
      - ./fixtures/ubuntu-14.04:/fixtures:ro
  debian-11:
    extends:
      file: docker-tests-base.yml
      service: run
    image: debian:11
    volumes:
      - ./fixtures/debian-11:/fixtures:ro
  debian-10:
    extends:
      file: docker-tests-base.yml
      service: run
    image: debian:10
    volumes:
      - ./fixtures/debian-10:/fixtures:ro
  debian-9:
    extends:
      file: docker-tests-base.yml
      service: run
    image: debian:9
    volumes:
      - ./fixtures/debian-9:/fixtures:ro
  openwrtorg:
    extends:
      file: docker-tests-base.yml
      service: run
    build:
      context: ./docker/openwrtorg
    volumes:
      - ./fixtures/openwrtorg:/fixtures:ro
  fedora-37:
    extends:
      file: docker-tests-base.yml
      service: run
    build:
      context: ./docker/fedora/37
    volumes:
      - ./fixtures/fedora-37:/fixtures:ro
  fedora-36:
    extends:
      file: docker-tests-base.yml
      service: run
    build:
      context: ./docker/fedora/36
    volumes:
      - ./fixtures/fedora-36:/fixtures:ro
  fedora-35:
    extends:
      file: docker-tests-base.yml
      service: run
    build:
      context: ./docker/fedora/35
    volumes:
      - ./fixtures/fedora-35:/fixtures:ro
  fedora-34:
    extends:
      file: docker-tests-base.yml
      service: run
    build:
      context: ./docker/fedora/34
    volumes:
      - ./fixtures/fedora-34:/fixtures:ro
  centos-7:
    extends:
      file: docker-tests-base.yml
      service: run
    image: centos:7
    volumes:
      - ./fixtures/centos-7:/fixtures:ro
  redhat-9:
    extends:
      file: docker-tests-base.yml
      service: run
    build:
      context: ./docker/redhat/9
    volumes:
      - ./fixtures/redhat-9:/fixtures:ro
  redhat-8:
    extends:
      file: docker-tests-base.yml
      service: run
    build:
      context: ./docker/redhat/8
    volumes:
      - ./fixtures/redhat-8:/fixtures:ro
  opensuse-tumbleweed:
    extends:
      file: docker-tests-base.yml
      service: run
    build:
      context: ./docker/opensuse/tumbleweed
    volumes:
      - ./fixtures/opensuse-tumbleweed:/fixtures:ro
  opensuse-leap-15:
    extends:
      file: docker-tests-base.yml
      service: run
    build:
      context: ./docker/opensuse/leap/15
    volumes:
      - ./fixtures/opensuse-leap-15:/fixtures:ro
